services:
  solr:
    image: solr:latest
    volumes:
      - $PWD/solr/conf:/opt/solr/conf
    ports:
      - 8983:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"
  geoserver:
    image: ghcr.io/geoblacklight/geoserver:2.25.3-dev
    ports:
      - 8080:8080
