# New GeoBlacklight v4.1 Settings

# Solr field mappings
FIELDS:
  :ACCESS_RIGHTS: 'dct_accessRights_s'
  :ALTERNATIVE_TITLE: 'dct_alternative_sm'
  :CENTROID: 'dcat_centroid'
  :CREATOR: 'dct_creator_sm'
  :DATE_ISSUED: 'dct_issued_s'
  :DATE_RANGE: 'gbl_dateRange_drsim'
  :DESCRIPTION: 'dct_description_sm'
  :DISPLAY_NOTE: 'gbl_displayNote_sm'
  :FORMAT: 'dct_format_s'
  :FILE_SIZE: 'gbl_fileSize_s'
  :GEOREFERENCED: 'gbl_georeferenced_b'
  :ID: 'id'
  :IDENTIFIER: 'dct_identifier_sm'
  :INDEX_YEAR: 'gbl_indexYear_im'
  :IS_PART_OF: 'dct_isPartOf_sm'
  :IS_REPLACED_BY: 'dct_isReplacedBy_sm'
  :THEME: 'dcat_theme_sm'
  :KEYWORD: 'dcat_keyword_sm'
  :LANGUAGE: 'dct_language_sm'
  :LAYER_MODIFIED: 'gbl_mdModified_dt'
  :LICENSE: 'dct_license_sm'
  :MEMBER_OF: 'pcdm_memberOf_sm'
  :METADATA_VERSION: 'gbl_mdVersion_s'
  :MODIFIED: 'gbl_mdModified_dt'
  :OVERLAP_FIELD: 'solr_bboxtype'
  :PUBLISHER: 'dct_publisher_sm'
  :PROVIDER: 'schema_provider_s'
  :REFERENCES: 'dct_references_s'
  :RELATION: 'dct_relation_sm'
  :REPLACES: 'dct_replaces_sm'
  :RESOURCE_CLASS: 'gbl_resourceClass_sm'
  :RESOURCE_TYPE: 'gbl_resourceType_sm'
  :RIGHTS: 'dct_rights_sm'
  :RIGHTS_HOLDER: 'dct_rightsHolder_sm'
  :SOURCE: 'dct_source_sm'
  :SPATIAL_COVERAGE: 'dct_spatial_sm'
  :GEOMETRY: 'locn_geometry'
  :SUBJECT: 'dct_subject_sm'
  :SUPPRESSED: 'gbl_suppressed_b'
  :TEMPORAL_COVERAGE: 'dct_temporal_sm'
  :TITLE: 'dct_title_s'
  :VERSION: 'dct_isVersionOf_sm'
  :WXS_IDENTIFIER: 'gbl_wxsIdentifier_s'

# Enable catalog#show sidebar static map for items with the following viewer protocols
SIDEBAR_STATIC_MAP:
  - 'iiif'
  - 'iiif_manifest'

# Relationships to display
RELATIONSHIPS_SHOWN:
  MEMBER_OF_ANCESTORS:
    field: pcdm_memberOf_sm
    query_type: ancestors
    icon: nil
    label: geoblacklight.relations.member_of_ancestors
  MEMBER_OF_DESCENDANTS:
    field: pcdm_memberOf_sm
    query_type: descendants
    icon: child-item
    label: geoblacklight.relations.member_of_descendants
  PART_OF_ANCESTORS:
    field: dct_isPartOf_sm
    query_type: ancestors
    icon: nil
    label: geoblacklight.relations.part_of_ancestors
  PART_OF_DESCENDANTS:
    field: dct_isPartOf_sm
    query_type: descendants
    icon: child-item
    label: geoblacklight.relations.part_of_descendants
  RELATION:
    field: dct_relation_sm
    query_type: ancestors
    icon: nil
    label: geoblacklight.relations.relation
  REPLACES_ANCESTORS:
    field: dct_replaces_sm
    query_type: ancestors
    icon: nil
    label: geoblacklight.relations.replaces
  REPLACES_DESCENDANTS:
    field: dct_replaces_sm
    query_type: descendants
    icon: nil
    label: geoblacklight.relations.replaced_by
  SOURCE_ANCESTORS:
    field: dct_source_sm
    query_type: ancestors
    icon: parent-item
    label: geoblacklight.relations.ancestor
  SOURCE_DESCENDANTS:
    field: dct_source_sm
    query_type: descendants
    icon: child-item
    label: geoblacklight.relations.descendant
  VERSION_OF_ANCESTORS:
    field: dct_isVersionOf_sm
    query_type: ancestors
    icon: parent-item
    label: geoblacklight.relations.version_of_ancestors
  VERSION_OF_DESCENDANTS:
    field: dct_isVersionOf_sm
    query_type: descendants
    icon: child-item
    label: geoblacklight.relations.version_of_descendants

# Display Notes to display / Non-prefixed default bootstrap class is alert-secondary
DISPLAY_NOTES_SHOWN:
  danger:
    bootstrap_alert_class: alert-danger
    icon: fire-solid
    note_prefix: "Danger: "
  info:
    bootstrap_alert_class: alert-info
    icon: circle-info-solid
    note_prefix: "Info: "
  tip:
    bootstrap_alert_class: alert-success
    icon: lightbulb-solid
    note_prefix: "Tip: "
  warning:
    bootstrap_alert_class: alert-warning
    icon: triangle-exclamation-solid
    note_prefix: "Warning: "