module Geoblacklight
  class Configuration
    # Configuration for fields used in GeoBlacklight search results and metadata display.
    class FieldsConfig
      include ActiveModel::Attributes

      attribute :access_rights, :string, default: "dct_accessRights_s"
      attribute :alternative_title, :string, default: "dct_alternative_sm"
      attribute :centroid, :string, default: "dcat_centroid"
      attribute :creator, :string, default: "dct_creator_sm"
      attribute :date_issued, :string, default: "dct_issued_s"
      attribute :date_range, :string, default: "gbl_dateRange_drsim"
      attribute :description, :string, default: "dct_description_sm"
      attribute :display_note, :string, default: "gbl_displayNote_sm"
      attribute :format, :string, default: "dct_format_s"
      attribute :file_size, :string, default: "gbl_fileSize_s"
      attribute :georeferenced, :string, default: "gbl_georeferenced_b"
      attribute :id, :string, default: "id"
      attribute :identifier, :string, default: "dct_identifier_sm"
      attribute :index_year, :string, default: "gbl_indexYear_im"
      attribute :is_part_of, :string, default: "dct_isPartOf_sm"
      attribute :is_replaced_by, :string, default: "dct_isReplacedBy_sm"
      attribute :theme, :string, default: "dcat_theme_sm"
      attribute :keyword, :string, default: "dcat_keyword_sm"
      attribute :language, :string, default: "dct_language_sm"
      attribute :license, :string, default: "dct_license_sm"
      attribute :member_of, :string, default: "pcdm_memberOf_sm"
      attribute :metadata_version, :string, default: "gbl_mdVersion_s"
      attribute :modified, :string, default: "gbl_mdModified_dt"
      attribute :overlap_field, :string, default: "solr_bboxtype"
      attribute :publisher, :string, default: "dct_publisher_sm"
      attribute :provider, :string, default: "schema_provider_s"
      attribute :references, :string, default: "dct_references_s"
      attribute :relation, :string, default: "dct_relation_sm"
      attribute :replaces, :string, default: "dct_replaces_sm"
      attribute :resource_class, :string, default: "gbl_resourceClass_sm"
      attribute :resource_type, :string, default: "gbl_resourceType_sm"
      attribute :rights, :string, default: "dct_rights_sm"
      attribute :rights_holder, :string, default: "dct_rightsHolder_sm"
      attribute :source, :string, default: "dct_source_sm"
      attribute :spatial_coverage, :string, default: "dct_spatial_sm"
      attribute :geometry, :string, default: "locn_geometry"
      attribute :subject, :string, default: "dct_subject_sm"
      attribute :suppressed, :string, default: "gbl_suppressed_b"
      attribute :temporal_coverage, :string, default: "dct_temporal_sm"
      attribute :title, :string, default: "dct_title_s"
      attribute :version, :string, default: "dct_isVersionOf_sm"
      attribute :wxs_identifier, :string, default: "gbl_wxsIdentifier_s"
    end
  end
end
